### ISSUE TITLE
Simple oversight: Small Edit allows for connect again after a disconnect (Websocket issue fix)

### ISSUE THREAD

**Issue by ClandestineCoder** [pusher-community/pusher-websocket-dotnet#13]
I'm really new to github, sorry if this is the wrong place to post this. I could find few other ways to contact the authors.

I discovered a simple issue to fix. I am also new to coding c#, but not new to "coding". The first thing I learned is dispose(); dispose(); dispose();

HAHA

Anyway, The problem I found with the disconnecting loses the websocket access and then it fails to connect again is simply in file Connection.cs : Near Line: 226

``` C#
        private void websocket_Closed(object sender, EventArgs e)
        {
            Pusher.Trace.TraceEvent(TraceEventType.Warning, 0, "Websocket connection has been closed");

            ChangeState(ConnectionState.Disconnected);
            _websocket.Dispose(); // Line: 226, This is the line I changed. It was ( _websocket = null; )

            if (_allowReconnect)
            {
                ChangeState(ConnectionState.WaitingToReconnect);
                Thread.Sleep(_backOffMillis);
                _backOffMillis = Math.Min(MAX_BACKOFF_MILLIS, _backOffMillis + BACK_OFF_MILLIS_INCREMENT);
                ChangeState(ConnectionState.Connecting);
                Connect();
            }
        }
```

Otherwise, I have found this PusherClient to work flawless.
Thanks for your time. Hope this helps.

**Comment by imaji** [comment]
Hi,

This has been corrected as advised in the next version.

Best regards,
John
