### ISSUE TITLE
Unbind method?

### ISSUE THREAD

**Issue by cherrr** [pusher-community/pusher-websocket-dotnet#16]
There is currently no unbind method. Right now when I bind to a channel, I have a boolean to know if I want to execute code in binding action or not. However, would it be possible to have an unbind method like there: https://pusher.com/docs/client_api_guide/client_events#unbind-events

**Comment by alexbooker** [comment]
Yes, there should absolutely be an `Unbind` method.

**Comment by cherrr** [comment]
thank you for helping!! after this method, I found every thing I needed for my usage. Really useful library, thanks!!

**Comment by hot-leaf-juice** [comment]
See #23 for progress on this.

**Comment by hot-leaf-juice** [comment]
fixed in 0.4.0
