### ISSUE TITLE
PusherOptions property Host is unused

### ISSUE THREAD

**Issue by kamape** [pusher-community/pusher-websocket-dotnet#18]
By settings the PusherOptions.Host property you guess that this will redirect the Pusher connection to the correct host (and by that, correct cluster).

This doesn't work and you have to specify the Host property on the Pusher class instead to make this work.

**Comment by Misiu** [comment]
@kamape I've created PR https://github.com/pusher-community/pusher-websocket-dotnet/pull/21 that fixes that. Could You try that instead?

**Comment by hot-leaf-juice** [comment]
fixed by #22
