### ISSUE TITLE
Sample application missing critical line?

### ISSUE THREAD

**Issue by robborden** [pusher-community/pusher-websocket-dotnet#19]
Don't you need "_pusher.Connect()" in here somewhere?  I couldn't get it to work without it using the most current NuGet package.

https://github.com/pusher-community/pusher-websocket-dotnet/blob/master/ExampleApplication/Program.cs

**Comment by Misiu** [comment]
@robborden  look at https://github.com/pusher-community/pusher-websocket-dotnet/blob/master/ExampleApplication/Program.cs#L70?

**Comment by robborden** [comment]
Wow.... I swear I ctrl+f after the sample code I pasted from there didn't work.  Thanks for pointing out my error.  :/
