### ISSUE TITLE
Add nuspec file

### ISSUE THREAD

**Issue by Misiu** [pusher-community/pusher-websocket-dotnet#25]
Currently on PusherClient [nuget site](https://www.nuget.org/packages/PusherClient/0.4.0) we can see that Microsoft is author or that package.
This can be fixed by adding .nuspec file, just like Newtonsoft JSON package (https://github.com/JamesNK/Newtonsoft.Json/blob/master/Build/Newtonsoft.Json.nuspec)
This would allow to add project url, license url and other information to nuget package page.

**Comment by imaji** [comment]
Hi,

We do have one in the root of the solution :)

Thanks!
John

**Comment by Misiu** [comment]
@imaji thanks for the update.
There was something with AssemblyInfo.cs (https://github.com/pusher-community/pusher-websocket-dotnet/commit/14529a8c7100259ab6ecfa3320dbde21a686052a#diff-bd9f0cc7f15279f0e61084ef850e7835)
because on nuget site for version 0.4.0 in Authors section there was Microsoft, now there is Pusher :)

https://www.nuget.org/packages/PusherClient/0.4.0
https://www.nuget.org/packages/PusherClient/0.5.1

Problem solved 😄

**Comment by imaji** [comment]
:)
