### ISSUE TITLE
Not connect

### ISSUE THREAD

**Issue by alinaKava** [pusher-community/pusher-websocket-dotnet#26]
PuserClient hasn't worked since 14(15) Feb in my app. It doesn't connect (State: Connecting-Disconnect-WaitingToReconnect). I tried https://github.com/pusher-community/pusher-websocket-dotnet/tree/master/ExampleApplication but the same.
![pasted image at 2017_02_16 05_19 pm](https://cloud.githubusercontent.com/assets/6782165/23027693/bf5fda52-f46d-11e6-9d9a-0d7942eca2a6.png)

**Comment by alinaKava** [comment]
Error in 
https://github.com/pusher-community/pusher-websocket-dotnet/blob/master/PusherClient/Connection.cs#L72 
HTTP/1.1 426 Upgrade Required

**Comment by k-watts** [comment]
Have your firewall settings changed? Your network may be blocking WebSocket connections over port 80. I was temporarily experiencing the same connecting issue and finally realized it corresponded to me switching to a different more restrictive vlan. Changing my pusher app to use SSL corrected this for me.

_pusher = new Pusher(your_pusher_key, new PusherOptions() { Encrypted = true });

**Comment by hot-leaf-juice** [comment]
@alinaKava I just tested this with a fresh clone on a fresh machine and can't reproduce. I think @k-watts is probably spot on with the suggestion to check your firewall.

**Comment by alinaKava** [comment]
@k-watts it helped. thanks.
