### ISSUE TITLE
Prebuilded dll

### ISSUE THREAD

**Issue by SergXIIIth** [pusher-community/pusher-websocket-dotnet#4]
Hello,

I am on VS2010 Express. So Nuget and manual build is not working out of the box.

Is it possible download builded dll some where?
Could you please share it?

**Comment by leggetter** [comment]
@SergXIIIth the README has been updated with details of how you can download the package that was published to NuGet and extract the DLL:
https://github.com/pusher-community/pusher-websocket-dotnet#direct-download
